spring.application.name=notes-api

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/notesdb
spring.datasource.username=bipulkumar
spring.datasource.password=

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080